from typing import Any, Iterable, Protocol


class DBSession(Protocol):
    def add(self, instance: Any) -> None: ...

    def delete(self, instance: Any) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def close(self) -> None: ...

    def refresh(self, instance: Any) -> None: ...

    def execute(self, statement: Any) -> Iterable[Any]: ...
